@base_url = http://localhost:8080


### Create a contact
POST {{base_url}}/api/contacts
Content-Type: application/json

{
  "first_name": "Rakesh",
  "last_name": "K",
  "email": "rakesh@codersgyan.com",
  "tags": [
    { "text": "purchased:mern" },
    {"text": "purchased:devops"}
  ]
}